### ISSUE TITLE
Missing shot .pt files?

### ISSUE THREAD

**Issue by varungupta31** [MoviePuzzle/MoviePuzzle#3]
In `dataset.py`,

```
if self.layer == '':
            self.data = torch.load(Path(self.root, f'{split}_ori.pt'))
        else:
            self.data = torch.load(Path(self.root, f'{split}_ori_shot.pt'))
```

The Baidu link provided has `train.pt` and `val.pt`, where are these files?

**Comment by varungupta31** [comment]
Also, assuming the files are a typo, the keys expected in the code,
```
return self.data[clip_id]['text'], self.data[clip_id]['img'], self.data[clip_id]['img_id'], self.data[clip_id]['shot_id'], self.data[clip_id]['scene_id']
```
are not present in the provided `.pt` files!

Is this repo in running condition?

**Comment by patrick-tssn** [comment]
Apologies for the delayed response. The files provided are designed to expedite processing. You are free to specify the format or name that best suits your needs. You can download our dataset from our website: https://moviepuzzle.github.io/. Due to certain circumstances, this repository has not been updated since its initial release. At present, I lack the energy required to continue its maintenance. I hope that future updates will be presented to you in a more refined manner. For your information, several individuals have successfully replicated comparable results. I regret any inconvenience caused. If I fail to receive notifications from this GitHub repository, please do not hesitate to alert me by emailing flagwyx@gmail.com. I am also open to the possibility of future collaboration.

**Comment by patrick-tssn** [comment]
> In `dataset.py`,
> 
> ```
> if self.layer == '':
>             self.data = torch.load(Path(self.root, f'{split}_ori.pt'))
>         else:
>             self.data = torch.load(Path(self.root, f'{split}_ori_shot.pt'))
> ```
> 
> The Baidu link provided has `train.pt` and `val.pt`, where are these files?

The shot file is used for ablation

**Comment by patrick-tssn** [comment]
To ensure the code runs correctly, I have tested it myself and found no bugs to report.
![record_1](https://github.com/MoviePuzzle/MoviePuzzle/assets/38104831/1e541715-bfb7-4338-935f-85d30d7db342)

**Comment by varungupta31** [comment]
@patrick-tssn Thanks for your elaborate response and the time you spent on this issue. 

Its been a while since I explored this work, and I have lost the precise knowledge of where things were getting stuck.

However, from what I can recall, the code gets stuck [here](https://github.com/MoviePuzzle/MoviePuzzle/blob/b879fabc25826b135b3c9b619f409ba14e56eb1e/utils/dataset.py#L122C1-L123C1)
```python
return self.data[clip_id]['text'], self.data[clip_id]['img'], self.data[clip_id]['img_id'], self.data[clip_id]['shot_id'], self.data[clip_id]['scene_id']
```
From the few logs I collected for myself, upon analyzing the provided `.pt` files, these are the keys the `.pt` files contained within `self.data`.

<img width="1222" alt="Screenshot 2024-03-06 at 12 23 10 AM" src="https://github.com/MoviePuzzle/MoviePuzzle/assets/51288316/3a2d224c-c173-4d9e-a6cf-9add1518c3da">

The log above is of observing the contents of the relevant `.pt` files, and it does not contain a key `text` which the code seems to want. I remember checking both of the provided `.pt` files, but could not figure this out.

>  For your information, several individuals have successfully replicated comparable results

I never meant the results could not be replicated and meant more to discuss a potential issue in perhaps the shared code or the provided `pt` files, but I don't know how to go around this `KeyError`. Perhaps, I am missing something.

Regarding running the code yourself, if you still have it set-up somewhere, do you mind sharing the contents of the [line](https://github.com/MoviePuzzle/MoviePuzzle/blob/b879fabc25826b135b3c9b619f409ba14e56eb1e/utils/dataset.py#L122C1-L123C1)? 
Something like -> `print(self.data[clip_id].keys())` this will help match our outputs of that line, and narrow the issue.

Glad to hear about a possible collaboration, I'll get in touch if something resonates.
Again, thank you for your help.

Best,
V

**Comment by patrick-tssn** [comment]
Hello, For your convenience, I have uploaded the preprocessed data that is compatible with the class `NewVideoReorderMovieNetDataFolder`. I hope this resolves your issue.
